using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Nieweb.Pdf;

/// <summary>
/// Fixed corporate PDF template (docs/phase-2.md §11.1). Every Nieweb
/// PDF report is composed inside <see cref="Compose"/> which lays
/// down the header (Nieweb wordmark + centred title + timestamp),
/// the sub-header strip (BSS Green Premium mark + rule), the body
/// (delegated to the caller), and the footer
/// (<c>Nieweb · Page N of M · generated by &lt;user&gt;</c>).
/// </summary>
/// <remarks>
/// The template deliberately drops Vieweb 1.6's per-report header /
/// footer knobs (see docs/phase-2.md §10.1 resolution #2). SVG assets
/// ship as embedded resources under
/// <c>Nieweb.Pdf.Assets.{logo,bss_green_premium_no_pod}.svg</c> so
/// the renderer does not depend on repo-relative file paths at run
/// time. The corresponding SVGs are copied from the top-level
/// <c>logo/</c> folder by the csproj at build time.
/// </remarks>
public sealed class NiewebPdfDocument
{
    /// <summary>Body composer supplied by each concrete report.</summary>
    public delegate void BodyBuilder(IContainer body);

    private readonly string _title;
    private readonly string _subtitle;
    private readonly string _generatedByDisplayName;
    private readonly string _footerNote;
    private readonly DateTimeOffset _generatedAt;
    private readonly TimeZoneInfo _timeZone;
    private readonly BodyBuilder _body;

    /// <param name="title">Report title, rendered centred in the header.</param>
    /// <param name="subtitle">Optional sub-header line (source + window). Empty renders no subtitle.</param>
    /// <param name="generatedByDisplayName">User-facing name of the caller, printed in the footer.</param>
    /// <param name="generatedAt">UTC generation instant (rendered ISO date + time in header).</param>
    /// <param name="body">Composes the body content into the caller-provided container.</param>
    /// <param name="timeZone">Optional display time zone (see <see cref="NiewebPdfTimestamps.Resolve"/>). Defaults to UTC when null.</param>
    /// <param name="footerNote">
    /// Optional extra footer segment (e.g. the data source) appended
    /// after <c>generated by &lt;user&gt;</c>. Empty renders nothing so
    /// the footer stays <c>Nieweb · Page N of M · generated by X</c>.
    /// </param>
    public NiewebPdfDocument(
        string title,
        string subtitle,
        string generatedByDisplayName,
        DateTimeOffset generatedAt,
        BodyBuilder body,
        TimeZoneInfo? timeZone = null,
        string? footerNote = null)
    {
        ArgumentException.ThrowIfNullOrEmpty(title);
        ArgumentNullException.ThrowIfNull(generatedByDisplayName);
        ArgumentNullException.ThrowIfNull(body);
        _title = title;
        _subtitle = subtitle ?? string.Empty;
        _generatedByDisplayName = generatedByDisplayName;
        _footerNote = footerNote ?? string.Empty;
        _generatedAt = generatedAt;
        _timeZone = timeZone ?? TimeZoneInfo.Utc;
        _body = body;
    }

    /// <summary>
    /// Compose the whole document into <paramref name="container"/>.
    /// The caller typically drives this through <see cref="Render(Stream)"/>
    /// which handles <c>Document.Create(...).GeneratePdf(stream)</c>
    /// wiring itself.
    /// </summary>
    public void Compose(IDocumentContainer container)
    {
        ArgumentNullException.ThrowIfNull(container);
        container.Page(page =>
        {
            page.Size(PageSizes.A4.Landscape());
            page.Margin(1.5f, Unit.Centimetre);
            page.DefaultTextStyle(t => t.FontSize(9).FontFamily(Fonts.Arial));
            page.Header().Element(ComposeHeader);
            page.Content().PaddingVertical(0.5f, Unit.Centimetre).Element(_body.Invoke);
            page.Footer().Element(ComposeFooter);
        });
    }

    /// <summary>Convenience: render this document to <paramref name="destination"/>.</summary>
    public void Render(Stream destination)
    {
        ArgumentNullException.ThrowIfNull(destination);
        NiewebPdfLicense.EnsureLicenseActivated();
        Document.Create(Compose).GeneratePdf(destination);
    }

    private void ComposeHeader(IContainer container)
    {
        container.Column(col =>
        {
            col.Item().Row(row =>
            {
                // Left flank: Nieweb wordmark. Left and right flanks
                // are pinned to the same width so the centre column's
                // AlignCenter actually places the title on the page's
                // horizontal midpoint (a 4.8 / flex / 4.5 layout
                // biased the title 3 mm right of centre and became
                // visible whenever the subtitle got long enough to
                // fill the middle column).
                row.ConstantItem(5.0f, Unit.Centimetre)
                   .Height(1.2f, Unit.Centimetre)
                   .Svg(BrandAssets.NiewebLogoSvg);

                // Centre: report title.
                row.RelativeItem().AlignCenter().AlignMiddle().Column(c =>
                {
                    c.Item().AlignCenter().Text(_title)
                        .FontSize(14).SemiBold().FontColor(Colors.Grey.Darken3);
                    if (!string.IsNullOrEmpty(_subtitle))
                    {
                        c.Item().AlignCenter().Text(_subtitle)
                            .FontSize(9).FontColor(Colors.Grey.Darken1);
                    }
                });

                // Right flank: generation timestamp in the caller's
                // display time zone (falls back to UTC when the
                // caller did not supply one).
                row.ConstantItem(5.0f, Unit.Centimetre).AlignRight().AlignMiddle()
                   .Text(NiewebPdfTimestamps.FormatInstant(_generatedAt, _timeZone))
                   .FontSize(9).FontColor(Colors.Grey.Darken1);
            });

            // Sub-header strip: BSS Green Premium mark + rule.
            col.Item().PaddingTop(2).Row(row =>
            {
                // Box aspect matches bss_green_premium_no_pod.svg
                // viewBox 900x110 (~8.18:1); 4.5cm × 0.55cm keeps the
                // aspect while fitting the sub-header strip.
                row.ConstantItem(4.5f, Unit.Centimetre)
                   .Height(0.55f, Unit.Centimetre)
                   .Svg(BrandAssets.BssGreenPremiumSvg);
                row.RelativeItem();
            });
            col.Item().PaddingTop(2).LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
        });
    }

    private void ComposeFooter(IContainer container)
    {
        container.AlignCenter().Text(text =>
        {
            text.DefaultTextStyle(t => t.FontSize(8).FontColor(Colors.Grey.Darken1));
            text.Span("Nieweb  ·  Page ");
            text.CurrentPageNumber();
            text.Span(" of ");
            text.TotalPages();
            text.Span("  ·  generated by ");
            text.Span(_generatedByDisplayName);
            if (!string.IsNullOrEmpty(_footerNote))
            {
                text.Span("  ·  ");
                text.Span(_footerNote);
            }
        });
    }
}

/// <summary>
/// Loads the SVG brand assets from the embedded resources bundled
/// into <c>Nieweb.Pdf</c> at build time. Cached on first read so the
/// SVG bytes are only pulled from the assembly manifest once per
/// process.
/// </summary>
internal static class BrandAssets
{
    private static readonly Lazy<string> _niewebLogo = new(
        () => LoadSvg("logo.svg"), isThreadSafe: true);

    private static readonly Lazy<string> _bssGreenPremium = new(
        () => LoadSvg("bss_green_premium_no_pod.svg"), isThreadSafe: true);

    public static string NiewebLogoSvg => _niewebLogo.Value;

    public static string BssGreenPremiumSvg => _bssGreenPremium.Value;

    private static string LoadSvg(string fileName)
    {
        var asm = typeof(BrandAssets).Assembly;
        var resourceName = $"Nieweb.Pdf.Assets.{fileName}";
        using var stream = asm.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException(
                $"Embedded resource '{resourceName}' not found. Available: {string.Join(", ", asm.GetManifestResourceNames())}.");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}
